import Head from "next/head"
import Header from "./Header"
import styles from 'styles/Home.module.sass'

export default function Layout({children}:any) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header/>
        {children}
      </main>
    </>
  )
}